config/routes.rb
Rails.application.routes.draw do

  resources :pages, only: [:show]
  resources :locations, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :programs, only: [:index, :show]

  devise_for :users

  root to: 'home#index'

  get   'bomb'        => 'home#bomb', :as => :bomb
  get   'home/index'
  match 'preferences' => 'preferences#edit', :as => :preferences, via: [:get, :patch]

  namespace :admin do
    resources :users do
      get :undelete, on: :member
    end
    resources :programs do
      get :sendmail, on: :member
    end
    resources :events do
      get :copy, on: :member
      get :set_status, on: :member
    end
    resources :pages
    resources :contents
    resources :flyers
    resources :locations
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @events_programm = Event.where(:ptype => '0').where("startdate > ?", ( DateTime.now - 31.day)).order(:startdate)
    #  p.startdate.day - DateTime.now.midnight.day
    @events_neues = Event.where(:ptype => '1').order(:startdate)
    @events_neues_published = Event.where(:ptype => '1').where(:status => 'Published').order(:startdate)
    @events_undsonst = Event.where(:ptype => '2').where("startdate > ?", ( DateTime.now - 1.day)).order(:startdate)

    @pages = Page.where(published: true).where(in_menu: true)
    @footer_pages = Page.where(published: true).where(in_footer: true)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_event.haml
- klass = "event event_mini"
- if p.status == 'Published'
  - klass += " event_published"
- else
  - klass += " event_draft"


%div{:class=>"#{klass}",:id=>"event_#{p.id}"}

  - if p.image && p.image.url
    %div{:class=>"image"}
      %img{:src=>"#{p.image.thumb.url}"}
  - if p.startdate
    %p
      %small
        = smart_date_display(p.startdate,p.enddate)
        - if p.ptype == "2"
          \|
          - if p.location
            = link_to p.location do
              = p.location.title
          - elsif p.locationtext.present?
            = p.locationtext
          - else
            ?
  %h4
    - if p.longtext.present?
      = link_to "#{p.title}", p
    - else
      = p.title
    - if can? :create, Event
      = render partial: "/partials/event_publish", locals: { p: p }


  - if p.shortext.present?
    %p= p.shortext
  - elsif p.longtext.present?
    %div= sanitize p.longtext.html_safe

app/views/home/index.haml
- if current_program.present?
  = render partial: '/partials/custom_styles', locals: {program: current_program}


- if ( can? :create, Event ) && ( can? :create, Location )
  .row.hide
    .columns.large-2
      %p
        = link_to "Programs", admin_programs_url, :class=>"button"
        %br
        #{Program.all.count} Programs
    .columns.large-2
      %p
        = link_to "Events", events_url, :class=>"button"
        %br
        #{Event.all.count} Events
    .columns.large-2
      %p
        = link_to "Locations", locations_url, :class=>"button"
        %br
        #{Location.all.count} Locations
    .columns.large-6
      &nbsp;

= render partial: "/partials/header"


#main_content
  .row
    .columns.medium-6.large-6
      .panel.hide
        %h3
          zakk
          %strong Programm
      - @events_programm.each do  |p|
        - if ( p.status == 'Published' ) || ( can? :manage, Event )
          .panel
            = render partial: "event", locals: { p: p }


      - if ( can? :create, Event )
        %p.panel.hint
          sorted by startdate, only future dates (and today)
    .columns.medium-6.large-6
      - if current_program.present? && current_program.image.url
        - image_url = "#{current_program.image.thumb.url}"
      - else
        - image_url = "#{image_url('zakk_pattern1.png')}"
      .panel.program_image
        .text
          .image
            = link_to program_path("current") do
              %img{:src=>"#{image_url}"}

      .panel             
        .text
          %p
            Aktuelles Monatsprogramm:
            %br
            = link_to program_path("current") do
              %strong #{current_program.title}

      - if @events_neues_published.count > 0 || ( can? :manage, Event )
        .panel.hide
          %h3
            Neues im
            %strong zakk
      
        .panel
          - @events_neues.each do  |p|
            - if ( p.status == 'Published' ) || ( can? :manage, Event )
              = render partial: "event", locals: { p: p }
        - if ( can? :create, Event )
          %p.panel.hint
            sorted by startdate, all events

    - if @events_undsonst.count > 0
      .columns.large-4
        - if @events_undsonst.count > 0
          .panel
            %h3
              Und
              %strong sonst
              ?
          - @events_undsonst.each do  |p|
            - if ( p.status == 'Published' ) || ( can? :manage, Event )
              = render partial: "event", locals: { p: p }
          - if ( can? :create, Event )
            %p.panel.hint
              sorted by startdate, only future dates (and today)
  .row
    .columns.large-4
      %p.text-right
        %span.ptext
          %a{:href=>"/"}
            %strong zakk
        %span.ptext
          %a{:href=>"/"}
            klubraum
    .columns.large-4
      #imagecredits
        - if current_program.image_credit.present? && current_program.image.url
          %span.ptext
            Bild:
            - if current_program.image_credit_link.present?
              = link_to "#{current_program.image_credit_link}" do
                = current_program.image_credit
            - else
              = current_program.image_credit
        - if current_program.backgroundimage_credit.present?
          %span.ptext
            - if current_program.image_credit.present? && current_program.backgroundimage_credit.present?
              Hintergrundbild:
            - else
              Bild:
            - if current_program.backgroundimage_credit_link.present?
              = link_to "#{current_program.backgroundimage_credit_link}" do
                = current_program.backgroundimage_credit
            - else
              = current_program.backgroundimage_credit
    .columns.large-4
      = render partial: "/partials/nav"
  .row
    .columns.large-12
      &nbsp;